server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8081

spring:
  datasource:
    password: 123456
    url: jdbc:postgresql://localhost:5432/sira
    username: postgres
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true


  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 7d65ed5b483ad6
    password: d8ad5dd73f0af5

    properties:
      mail:
        smtp:
          ssl: no
          auth: PLAIN
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
